name:                assert4hs-hspec
version:             0.1.0
github:              "paweln1986/assert4hs-hspec"
license:             "MIT"
author:              "Pawel Nosal"
maintainer:          "p.nosal1986@gmail.com"
copyright:           "2021 Pawel Nosal"
license-file:        "LICENSE.md"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            integration point of assert4hs and hspec
category:            Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/assert4hs-hspec#readme>

dependencies:
- base >= 4.7 && < 5
- assert4hs-core
- hspec
- HUnit

library:
  source-dirs: src
  reexported-modules:
    - Test.Fluent.Assertions
    - Test.Fluent.Assertions.Maybe
    - Test.Fluent.Assertions.List
    - Test.Fluent.Assertions.Exceptions
    - Test.Fluent.Assertions.Either
    - Test.Fluent.Diff
tests:
  assert4hs-hspec-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assert4hs-hspec
